services:
#  grafana-lgtm:
#    image: 'grafana/otel-lgtm:latest'
#    ports:
#      - '3000:3000'
#      - '4317'
#      - '4318'
  postgres:
    image: 'pgvector/pgvector:pg18'
    environment:
      - 'POSTGRES_DB=spring_notes'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:4-management'
    ports:
      - '5672'
      - '15672'
