spring:
  application:
    name: spring-notes
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_notes
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
