spring:
  application:
    name: spring-notes
  data:
    jdbc:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_notes
    username: postgres
    password: postgres
  threads:
    virtual:
      enabled: true
#  docker:
#    compose:
#      enabled: false